@host = http://127.0.0.1:8000
@device_token = 091de3bc8f2335bf5044e221ba05324c2e69496eac6f365bc0bb9a753e81e3c1

### 1. Kiosk login - vymeni rfid_uid "000000" za Bearer session token
# @name login
POST {{host}}/api/auth/rfid-login/
X-Device-Token: {{device_token}}
Content-Type: application/json

{
  "rfid_uid": "000000"
}
### 2. Zoznam notifikacii prihlaseneho usera

# @name notifications
GET {{host}}/api/notifications/
Authorization: Bearer {{login.response.body.token}}

### 2.1 Zoznam neprecitanych notifikacii prihlaseneho usera
GET {{host}}/api/notifications/unread/
Authorization: Bearer {{login.response.body.token}}


### 2.2 Mark as read - oznaci notifikaciu ako precitanu
PATCH {{host}}/api/notifications/mark-as-read/{{notifications.response.body.results.0.id}}/
Authorization: Bearer {{login.response.body.token}}


### 3. Bez Bearer - kontrola
GET {{host}}/api/notifications/
