# Generated by Django 5.2.16 on 2026-07-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_attachment_etag_attachment_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='converted_to_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
