# Generated by Django 5.2.16 on 2026-08-07 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_number_version_label'),
        ('users', '0002_user_is_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('ALL', 'Všetci používatelia'), ('BUSINESS_UNIT', 'Business unit'), ('PROFESSION_CATEGORY', 'Profession category'), ('BOTH', 'Business unit A profession category'), ('USER', 'Konkrétny používateľ')], max_length=30)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('business_units', models.ManyToManyField(blank=True, related_name='document_assignments', to='users.businessunit')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.documentversion')),
                ('profession_categories', models.ManyToManyField(blank=True, related_name='document_assignments', to='users.professioncategory')),
                ('users', models.ManyToManyField(blank=True, related_name='document_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Priradenie dokumentu',
                'verbose_name_plural': 'Priradenia dokumentov',
                'ordering': ['document_version_id', 'target_type'],
            },
        ),
    ]
