# Generated by Django 5.2.16 on 2026-08-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_required_to_assignments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentVisibilityRule',
        ),
    ]
