"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# V produkcii nastav SECRET_KEY v .env (nizsie default je len pre lokalny vyvoj).
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-fmr-xtd67*jkpe108mx-xx-%!d6yjwi0$ci#x5#(anazwg-y^w',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# napr. ALLOWED_HOSTS=kiosk.firma.sk,10.0.0.5 v .env pre produkciu
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost,testserver', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'django_celery_beat',
    'corsheaders',
    'django_filters',
    'drf_spectacular',

    'core',
    'users',
    'documents',
    'signatures',
    'rfid_auth',
    'integrations',
    'notifications',

    'kiosk',
]

# Microsoft Graph / SharePoint (app-only, client-credentials)
AZURE_TENANT_ID = config('TENANT_ID')
AZURE_CLIENT_ID = config('APP_ID')
AZURE_CLIENT_SECRET = config('SECRET')

SP_HOSTNAME = config('SP_HOSTNAME', default='tatravagonkask.sharepoint.com')
SP_SITE_PATH = config('SP_SITE_PATH', default='/sites/acRd')
SP_SITE_ID = config('SP_SITE_ID', default='')
SP_LIST_PLATNE_ID = config('SP_LIST_PLATNE_ID', default='')
SP_LIST_PRILOHY_ID = config('SP_LIST_PRILOHY_ID', default='')
SP_PRILOHY_DRIVE_ID = config('SP_PRILOHY_DRIVE_ID', default='')

AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'rfid_auth.backends.RfidBackend',
]

RFID_SESSION_TTL = timedelta(seconds=config('RFID_SESSION_TTL_SECONDS', default=600, cast=int))

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'kiosk.middleware.RfidSessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rfid_auth.authentication.RfidSessionAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_RATES': {
        'rfid_login': '60/min',  # ochrana kiosk login endpointu proti brute-force rfid_uid
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

CORS_ALLOW_ALL_ORIGINS = True  # zatial pre dev NEZABUDNI !!!

SPECTACULAR_SETTINGS = {
    'TITLE': 'MIDo App API',
    'DESCRIPTION': 'Backend pre spravu internej dokumentacie, RFID kiosky a elektronicke podpisy.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Bratislava'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (locally stored PDF snapshots of documents/attachments)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Celery
from celery.schedules import crontab  # noqa: E402

CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_TASK_ALWAYS_EAGER = config('CELERY_TASK_ALWAYS_EAGER', default=False, cast=bool)
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BEAT_SCHEDULE = {
    'sync-documents-daily': {
        'task': 'documents.sync_documents',
        'schedule': crontab(hour=3, minute=0),
    },
    'sweep-attachments-weekly': {
        'task': 'documents.sweep_attachments',
        'schedule': crontab(hour=4, minute=0, day_of_week='sunday'),
    },
    'cleanup-sessions-daily': {
        'task': 'rfid_auth.cleanup_sessions',
        'schedule': crontab(hour=2, minute=30),
    },
    'send-reminders-daily': {
        'task': 'notifications.send_reminders',
        'schedule': crontab(hour=6, minute=0),
    },
}

# Logging
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

APP_LOGGERS = ['documents', 'rfid_auth', 'integrations', 'signatures', 'users', 'core', 'celery']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        logger_name: {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        }
        for logger_name in APP_LOGGERS
    },
}
